# Generated by Django 4.0.2 on 2022-03-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_watchlist_item_id_alter_watchlist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
