# Generated by Django 4.0.2 on 2022-03-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.item'),
        ),
    ]
