# Generated by Django 4.0.2 on 2022-03-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_categories_alter_watchlist_id_itemcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
