# Generated by Django 4.0.2 on 2022-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_item_owner_id_delete_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isActive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
