# Generated by Django 4.0.2 on 2022-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_item_lastbidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
