# Generated by Django 4.0.2 on 2022-05-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_item_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
